### ISSUE TITLE
Автотесты.

### ISSUE THREAD

**Issue by vb64** [yandex/alice-skills#4]
Здравствуйте.

Насчет "мы принимаем пулреквесты". Могу сделать пулреквест с примером автотестов для навыков на flask с использованием моего класса, сделанного для этой цели:
https://github.com/vb64/test.helper.yandex.alice.flask

Нужно?

**Comment by ykalchevskiy** [comment]
@vb64, сделайте pull-request в https://github.com/sameoldmadness/awesome-alice

**Comment by vb64** [comment]
> @vb64, сделайте pull-request в https://github.com/sameoldmadness/awesome-alice

https://github.com/sameoldmadness/awesome-alice/pull/19

**Comment by sameoldmadness** [comment]
merged
